name: Deploy dev to AWS

#turn off deploy to AWS
on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: |
          # Ensure .env file exists before moving
          if [ -f .env ]; then
            mv .env dist
          else
            echo ".env file does not exist, skipping move"
          fi
      
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1